version: '3.8'
services:
  mongodb:
    container_name: mongodb
    image: 'mongo'
    volumes:
      - data:/data/db
    # for environment variables we can either add them right here:
    # environment:
    #   - MONGO_INITDB_ROOT_USERNAME=mosari307
    #   - MONGO_INITDB_ROOT_PASSWORD=aaa???123A
    # or using a file :
    env_file:
      - ./env/mongo.env
  backend:
    container_name: app-back-ctn
    # if you want docker-compose to build the image for you
    build: ./backend
    # ||
    # build: 
    #   context: ./backend
    #   dockerfile: dockerfile
    #   here you can specify arguments
    #   args:
    #     - some_arg=value
    # 
    # else if ==> you have the built image and you just want d-compose to use it:
    # image: 'app-back-img'
    ports:
      - '80:80'
    volumes:
      - logs:/app/logs
      - ./backend:/app
      - /app/node_modules
    env_file:
      - ./env/backend.env
    depends_on:
      - mongodb
  frontend:
    container_name: app-front-ctn
    image: 'app-front-img'
    ports:
      - '3000:3000'
    volumes:
      - ./frontend/src:/app/src
    stdin_open: true
    tty: true
    depends_on:
      - backend


# we must specify named volumes here only, not anonymous volumes or bindMounts
volumes:
  data:
  logs: